wip: responsive enhancements
unoplatform/uno.toolkit.ui pull request #944
Opened 2023-12-04 19:55 UTC by Xiaoy312

GitHub Issue (If applicable): #

## PR Type
What kind of change does this PR introduce?
- Feature

## What is the current behavior?
## What is the new behavior?

## PR Checklist
Please check if your PR fulfills the following requirements:
- [ ] Tested code with current [supported SDKs](../README.md#supported)
- [ ] Tested the changes where applicable:
	- [ ] UWP
	- [ ] WinUI
	- [ ] iOS
	- [ ] Android
	- [ ] WASM
	- [ ] MacOS
- [ ] Updated the documentation as needed:
	- [ ] [General Doc Update](https://github.com/unoplatform/uno.toolkit.ui/tree/main/doc)
	- [ ] [Controls Doc Update](https://github.com/unoplatform/uno.toolkit.ui/tree/main/doc/controls)
	- [ ] [Extensions Doc Update](https://github.com/unoplatform/uno.toolkit.ui/tree/main/doc/helpers)
	- [ ] [controls-styles.md](https://github.com/unoplatform/uno.toolkit.ui/blob/main/doc/controls-styles.md)
	- [ ] [lightweight-styling.md (LightWeight Styling Resource Keys)](https://github.com/unoplatform/uno.toolkit.ui/blob/main/doc/lightweight-styling.md)
- [ ] [Runtime Tests and/or UI Tests](https://platform.uno/docs/articles/contributing/guidelines/creating-tests.html) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal)
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

2023-12-04 19:55 UTC, Xiaoy312 commented
saving top comment

2023-12-06 17:22 UTC, kazo0 approved these changes

2023-12-06 17:49 UTC, kazo0 reviewed
We'll need runtime tests for the layout resolution and type conversion

2023-12-06 18:02 UTC, eriklimakc requested changes

2023-12-06 18:02 UTC, eriklimakc commented on doc/helpers/responsive-extension.md
> +You can workaround this, by declaring the values are resources and use `{StaticResource}` to refer to them:
```suggestion
You can workaround this by declaring the values as resources and using {StaticResource} to refer to them:
```

2023-12-06 18:13 UTC, Xiaoy312 commented on doc/controls/ResponsiveView.md
> +> - from the hardcoded `ResponsiveHelper.Layout`
I feel this will just bloat up the docs. This is concise and detailed enough.

2023-12-06 18:45 UTC, silviuo commented on doc/controls/ResponsiveView.md
> +> It is not necessary to define every template or layout breakpoints: Narrowest,Narrow,Normal,Wide,Widest. You can just define the bare minimum needed.
It is not necessary to define every template or layout breakpoint: Narrowest, Narrow, Normal, Wide, Widest. You can just define the bare minimum needed.

2023-12-06 18:54 UTC, eriklimakc approved these changes

2023-12-06 18:59 UTC, silviuo commented on doc/controls/ResponsiveView.md
> +> This `ResponsiveLayout` can also be provided from different locations. In the order of precedences, they are:
In the order of precedences > In order of precedence

2023-12-06 19:11 UTC, Xiaoy312 commented
> We'll need runtime tests for the layout resolution and type conversion

ill work on that, in the follow pr for performance
type conversion cant exactly be tested, since xaml parsing of markup is not supported: unoplatform/uno#14620

2023-12-06 19:19 UTC, silviuo approved these changes

2023-12-06 22:00 UTC, agneszitte approved these changes

2023-12-06 22:25 UTC, merged